//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the avt_vimba_camera package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __avt_vimba_camera__AVTVIMBACAMERACONFIG_H__
#define __avt_vimba_camera__AVTVIMBACAMERACONFIG_H__

namespace avt_vimba_camera
{
  class AvtVimbaCameraConfigStatics;

  class AvtVimbaCameraConfig
  {
  public:
    std::string frame_id_;
    std::string camera_ip_addr;
    std::string trig_timestamp_topic;
    std::string acquisition_mode;
    double acquisition_rate;
    std::string trigger_source;
    std::string trigger_mode;
    std::string trigger_selector;
    std::string trigger_activation;
    double trigger_delay;
    double exposure;
    std::string exposure_auto;
    std::string exposure_auto_alg;
    int exposure_auto_tol;
    int exposure_auto_max;
    int exposure_auto_min;
    int exposure_auto_outliers;
    int exposure_auto_rate;
    int exposure_auto_target;
    double gain;
    std::string gain_auto;
    int gain_auto_tol;
    double gain_auto_max;
    double gain_auto_min;
    int gain_auto_outliers;
    int gain_auto_rate;
    int gain_auto_target;
    double balance_ratio_abs;
    std::string balance_ratio_selector;
    std::string whitebalance_auto;
    int whitebalance_auto_tol;
    int whitebalance_auto_rate;
    int binning_x;
    int binning_y;
    int decimation_x;
    int decimation_y;
    int width;
    int height;
    int roi_width;
    int roi_height;
    int roi_offset_x;
    int roi_offset_y;
    std::string pixel_format;
    int stream_bytes_per_second;
    std::string ptp_mode;
    std::string sync_in_selector;
    std::string sync_out_polarity;
    std::string sync_out_selector;
    std::string sync_out_source;
    int iris_auto_target;
    std::string iris_mode;
    int iris_video_level_min;
    int iris_video_level_max;
  };
}

#endif // __AVTVIMBACAMERARECONFIGURATOR_H__